# Generated by Stub Gen (version: 0)

class Owner:
    def __init__(self, name: str=None, email: str=None, username: str=None):
        self.name: str = name
        self.email: str = email
        self.username: str = username


class Uploader:
    def __init__(self, name: str=None, email: str=None, username: str=None):
        self.name: str = name
        self.email: str = email
        self.username: str = username


class Author:
    def __init__(self, name: str=None, email: str=None, username: str=None):
        self.name: str = name
        self.email: str = email
        self.username: str = username


class CurrentPatchSet:
    def __init__(self, number: int=None, revision: str=None, parents: list=None, ref: str=None, uploader: Uploader=None, createdOn: int=None, author: Author=None, kind: str=None, approvals: list=None, sizeInsertions: int=None, sizeDeletions: int=None):
        self.number: int = number
        self.revision: str = revision
        self.parents: list = parents
        self.ref: str = ref
        self.uploader: Uploader = uploader
        self.createdOn: int = createdOn
        self.author: Author = author
        self.kind: str = kind
        self.approvals: list = approvals
        self.sizeInsertions: int = sizeInsertions
        self.sizeDeletions: int = sizeDeletions


class Change:
    def __init__(self, project: str=None, branch: str=None, id: str=None, number: int=None, subject: str=None, owner: Owner=None, url: str=None, commitMessage: str=None, createdOn: int=None, lastUpdated: int=None, open: bool=None, status: str=None, currentPatchSet: CurrentPatchSet=None):
        self.project: str = project
        self.branch: str = branch
        self.id: str = id
        self.number: int = number
        self.subject: str = subject
        self.owner: Owner = owner
        self.url: str = url
        self.commitMessage: str = commitMessage
        self.createdOn: int = createdOn
        self.lastUpdated: int = lastUpdated
        self.open: bool = open
        self.status: str = status
        self.currentPatchSet: CurrentPatchSet = currentPatchSet

