#!/bin/bash -e

# Synchronize local directory to remote machine destination

####### VARIABLES ###########

script_dir=$(dirname $BASH_SOURCE)

rsync_log=/tmp/sync2vm-rsync.log
ignore_file=$script_dir/ignore_modules

####### FUNCTIONS ###########

########## MAIN #############

# load sync-to-remote configuration
if [ -f ~/.devkit_config/sync2vm.conf ]; then
 . ~/.devkit_config/sync2vm.conf
else
 . $script_dir/config
fi

# sync (upload) to remote server
rsync -av --delete --exclude-from $ignore_file $src/ $dest/ --log-file=$rsync_log

########## END #############
